language: php

php:
    - 7.0
    - 7.1
    - 7.2

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

script:
    - vendor/bin/phpstan analyse -l 7 -c phpstan.neon src/App src/Bootstrap src/Config src/Exception src/Helper
    #- vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    #- bash <(curl -s https://codecov.io/bash)
