# Use the Trusty Ubuntu distribution AKA Ubuntu 14.04
dist: trusty

# Add Google Chrome to installation
addons:
  chrome: stable

# Install PHP
language: php

php:
    - 7.0
    - 7.1
    - 7.2

# Install Java
jdk: oraclejdk8

# Install
services:
    - mysql

# Install Selnium and the Selenium Chrome Driver and start Selenium
install:
    # Make Selenium directory
    - sudo mkdir /usr/local/share/selenium
    # Download Selenium to Selenium directory
    - sudo wget http://selenium-release.storage.googleapis.com/3.11/selenium-server-standalone-3.11.0.jar -P /usr/local/share/selenium
    # Download Selenium Chrome driver zip file
    - sudo wget https://chromedriver.storage.googleapis.com/2.37/chromedriver_linux64.zip -P /usr/local/share
    # Unzip Chrome driver
    - sudo unzip /usr/local/share/chromedriver_linux64.zip -d /usr/local/share
    # Delete Chrome driver zip
    - sudo rm /usr/local/share/chromedriver_linux64.zip
    # Run Selenium with Chrome driver, and attempt to suppress output
    - java -jar -Dwebdriver.chrome.driver="/usr/local/share/chromedriver" /usr/local/share/selenium/selenium-server-standalone-3.11.0.jar >/dev/null 2>&1 &

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev
    # Move into public directory
    - cd public
    # Start PHP server in public directory so requests route correctly and supress output
    - php -S 127.0.0.1:8000 >/dev/null 2>&1 &
    # Sleep to make sure PHP server has started
    - sleep 3
    # Move out of public directory so Behat can be executed
    - cd ../
    # Set up MySQL
    - mysql -e "create database test"
    # Set up Env
    - touch .env
    - echo "ENVIRONMENT=development" >> .env
    - echo "DB_HOST=127.0.0.1" >> .env
    - echo "DB_USER=travis" >> .env
    - echo "DB_PASSWORD=" >> .env
    - echo "DB_NAME=test" >> .env
    - echo "DB_PREFIX=wp_" >> .env
    - echo "DB_CHARSET=utf8" >> .env
    - echo "DB_COLLATE=utf8_unicode_ci" >> .env
    - echo "WP_DEBUG=true" >> .env
    - echo "WP_DEBUG_LOG=false" >> .env
    - echo "SSL=false" >> .env
    - vendor/bin/wpsalts dotenv  --clean >> .env
    - sleep 3


script:
    - vendor/bin/phpstan analyse -l 7 -c phpstan.neon src/App
    - vendor/bin/behat
    #- vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    #- bash <(curl -s https://codecov.io/bash)
